name: Cron dagcargo Populate Content DAG Sizes

on:
  schedule:
    - cron: '38 * * * *'
  workflow_dispatch:

jobs:
  update:
    name: Populate Missing Content DAG Sizes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ['staging', 'production']
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: bahmutov/npm-install@v1
      - name: Run job
        env:
          DEBUG: '*'
          ENV: ${{ matrix.env }}
          STAGING_PG_CONNECTION: ${{ secrets.STAGING_PG_CONNECTION }}
          PROD_PG_CONNECTION: ${{ secrets.PROD_PG_CONNECTION }}
        run: npm run start:dagcargo:sizes -w packages/cron

      - name: Heartbeat
        if: ${{ success() }}
        run: ./packages/tools/scripts/cli.js heartbeat --token ${{ secrets.OPSGENIE_KEY }} --name cron-web3storage-dagcargo-sizes